// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9jq2unOPZpFDGgE2tDtqqT6GC7HhjHM',
    appId: '1:1056427062809:web:d524cbd04bcfad35d3dc88',
    messagingSenderId: '1056427062809',
    projectId: 'kelompok1-pa-mobile-b221',
    authDomain: 'kelompok1-pa-mobile-b221.firebaseapp.com',
    storageBucket: 'kelompok1-pa-mobile-b221.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1rXJ-mcv8znyfEEmHyslUWPex8OYoww',
    appId: '1:1056427062809:android:92d5b74187f83f19d3dc88',
    messagingSenderId: '1056427062809',
    projectId: 'kelompok1-pa-mobile-b221',
    storageBucket: 'kelompok1-pa-mobile-b221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7z2BWWhGFVITKuXCLrzTR3bwgX7SOOD8',
    appId: '1:1056427062809:ios:98130ef5cc998dd1d3dc88',
    messagingSenderId: '1056427062809',
    projectId: 'kelompok1-pa-mobile-b221',
    storageBucket: 'kelompok1-pa-mobile-b221.appspot.com',
    iosBundleId: 'com.example.paMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7z2BWWhGFVITKuXCLrzTR3bwgX7SOOD8',
    appId: '1:1056427062809:ios:0de552e7ccd095edd3dc88',
    messagingSenderId: '1056427062809',
    projectId: 'kelompok1-pa-mobile-b221',
    storageBucket: 'kelompok1-pa-mobile-b221.appspot.com',
    iosBundleId: 'com.example.paMobile.RunnerTests',
  );
}
